---
title: "Statistical Methods in Sports: Preliminaries"
author: "Ryan Elmore"
date: "10/12/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Note(s):

* Complete the following steps in order to complete the homework assignment.

    1. Download [R](https://cran.r-project.org/) and [RStudio](https://www.rstudio.com/products/RStudio/#Desktop). Print and refer to this 
[RMarkdown cheatsheet](http://shiny.rstudio.com/articles/rm-cheatsheet.html). 

    2. Create a new Markdown file by going to -- `File` -- `New file` --
    `RMarkdown` and selecting `PDF`.
    
    3. Save the file as `Homework-0.Rmd` and make sure to enter your name where
    it says `Author.`
    
    4. Answer the questions given in the homework assignment. Upon completion,
    click `Knit HTML` at the top of RStudio, and print the resulting document.
    *Note*: Turn in the completed html file. 

* You will only need to do steps (2) - (4) on future homework assignments. 

### Questions

1. What math or stats classes have you taken while at college?  What
experience do you have using R or RStudio?

    Answer here:
    
2. What sports do you or have you participated in, and what ones do you watch
frequently?

    Answer here:

3. There are some excellent Markdown resources. In addition to the 
[RMarkdown cheatsheet](http://shiny.rstudio.com/articles/rm-cheatsheet.html), 
check out the work of Professor [Jenny Bryan](https://stat545-ubc.github.io/index.html), which includes [tips for first-time R users](https://stat545-ubc.github.io/block002_hello-r-workspace-wd-project.html), [basic data manipulation steps](https://stat545-ubc.github.io/block006_care-feeding-data.html), and [different R objects](https://stat545-ubc.github.io/block004_basic-r-objects.html)

    Using the information above, write five things about the R software that you
    did not know beforehand. 

    Answer here:

Remember to Knit the document! 

